### ISSUE TITLE
Do you have instructions for the latest Safari?

### ISSUE THREAD

**Issue by alberttwong** [kfatehi/GPGmail.safariextension#1]
Just curious if this is still alive.

**Comment by kfatehi** [comment]
Hi @alberttwong 

I would suspect that the Gmail redesigns have disabled it by now. It would most likely take some effort, but this is a good starting point. It was a feature I first created in an electron-based Gmail wrapper https://github.com/kfatehi/modmail and then later extracted as a safari extension.

As for installation, I dont recall, but two ways you could try:
* open up the safari extension building interface and see what it gives you and replace it.
* search on google for how to package these https://medium.com/streak-developer-blog/how-to-build-a-safari-extension-using-the-command-line-351394082ec1

it actually might be just as easy as saving the directory down and letting it have the name .safariextension and then apple makes it clickable, I dont remember. But I hope the feedback helps.
